---
title: "Øving 6"
output: pdf_document
date: '2022-05-30'
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize",fig.width=4, fig.height=3,fig.align = "center")
```

__Problem 1__

Perform polynomial regression of degree 1,2,3 and 4. Use lines() to add the fitted values in the plot. Also plot the test error depending on polynomial degree.

```{r,eval=TRUE}
library(ISLR)

ds = Auto[c("horsepower", "mpg")]
n = nrow(ds)

degrees = 1:4

set.seed(1)

train_id = sample.int(n,n/2)

plot(ds[train_id,], col = "darkgrey", main = "Polynomial regression")

co = rainbow(length(degrees))


MSE = sapply(degrees,function(d){
  model = lm(mpg ~ poly(horsepower, degree = d), data = ds[train_id,])
  lines(cbind(ds[train_id,1],model$fitted.values)[order(ds[train_id,1]),], col=co[d])
  mean((predict(model, ds[-train_id,])-ds[-train_id,2])^2)
})

legend("topright", legend = paste("d = ", degrees), lty = 1, col = co)

```


```{r,eval=TRUE}

MSE = data.frame(MSE = MSE, degree = 1:4)

ggplot(data = MSE, aes(x = degree, y = MSE)) + geom_line() + geom_point() + labs(title = "Test error")
```

__Problem 2__

Use factor(origin) for conversion to factor variable for the origin variable. Predict mpg by origin with a linear model. Plot the fitted values and approximate 95% confidence intervals.
